- name: Copy Kubeconfig files to worker nodes
  hosts: kube_node
  gather_facts: no
  tasks:

  - name: Get kubeconfig from master node
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: /tmp/admin.conf
      flat: yes
    become: yes
    delegate_to: kube-master1

  - name: Ensure .kube directory exists
    file:
      path: /root/.kube
      state: directory
    become: yes

  - name: Copy kubeconfig to worker nodes
    copy:
      src: /tmp/admin.conf
      dest: /root/.kube/config
    become: yes

  - name: Check if kubeconfig exists on worker nodes
    stat:
      path: /root/.kube/config
    become: yes
    register: kubeconfig_stat

  - debug:
      msg: "/root/.kube/config exists on the worker node."
    when: kubeconfig_stat.stat.exists

  - name: Ensure .kube directory exists in /home/vagrant
    file:
      path: /home/vagrant/.kube
      state: directory
      owner: vagrant
      group: vagrant
      mode: '0755'

  - name: Copy kube config to /home/vagrant/.kube
    command:
      cmd: cp /root/.kube/config /home/vagrant/.kube/config
      warn: false # This is optional; it prevents warnings about using shell commands.
    become: yes
    become_user: root

  - name: Change file ownership and permissions
    file:
      path: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant
      mode: '0644'
  become: yes

